### ISSUE TITLE
[bug] --help and --version options are interpretted as input

### ISSUE THREAD

**Issue by M4rtinK** [sailfishos/libsailfishapp#14]
sailfish-qml intrepretes both --help and --version as input and tries to run them:

<pre>
[nemo@Jolla ~]$ sailfish-qml --help
[D] QWaylandEglIntegration::QWaylandEglIntegration:58 - Using Wayland-EGL 
[D] MDesktopEntryPrivate::MDesktopEntryPrivate:126 - Specified Desktop file does not exist "/usr/share/applications/--help.desktop" 
[W] unknown:-1 - file:///usr/share/--help/qml/--help.qml: File not found 
</pre>

<pre>
[nemo@Jolla ~]$ sailfish-qml --version
[D] QWaylandEglIntegration::QWaylandEglIntegration:58 - Using Wayland-EGL 
[D] MDesktopEntryPrivate::MDesktopEntryPrivate:126 - Specified Desktop file does not exist "/usr/share/applications/--version.desktop" 
[W] unknown:-1 - file:///usr/share/--version/qml/--version.qml: File not found 
</pre>

Expected outcome:
--help returns usage instructions and --version returns sailfish-qml version

**Comment by martyone** [comment]
Nowadays it says

`[W] unknown:0 - Usage:  sailfish-qml  <appname> [<qt-option>...]`
