### ISSUE TITLE
[RFE] support for passing arguments to applications in sailfish-qml

### ISSUE THREAD

**Issue by M4rtinK** [sailfishos/libsailfishapp#16]
sailfish-qml currently only accepts one possitional argument, which is the application name. Appending any additional arguments results in an error. This prevents application that are being launched by sailfish-qml from receiving custom CLI argument and options.

Suggestion:
- arguments passed after the application name should be added to argv, example:
  <pre>sailfish.qml harbour-foo --bar baz</pre>
  should result in Qt.application.arguments being equal to:
  <pre>sailfish-qml,harbour-modrana,-bar,baz</pre>
- if #14 is fixed, my suggestion is to only handle _--help_ and _--version_ if no application name is provided, if application name is provided _--help_ and _--version_ should be added to agv and not handled so that the application can handle it itself
- if #15 is fixed, the import path option flag & path should be handled & appened to argv, which is what qmlscene does & the flag should be something that does not collide with often used flag names, for example _-I_ as with qmlscene or _--qml_import_path_append_

Usecase:
The modRana navigation system has [various command line options](http://modrana.org/trac/wiki/SystemFunctionalityEN#CommandLineOptions) and if _sailfish-qml_ adds support for option passing, it will be possible for users and
other applications to make use of them. For example:

<pre>
sailfish-qml harbour-modrana --local-search "pizza"
</pre>

or

<pre>
sailfish-qml harbour-modrana --focus-on-coordinates geo:50.083333,14.416667
</pre>

**Comment by M4rtinK** [comment]
Any takers/progress on this ? I'm afraid I've not progressed much in my C++ knowledge since I have filled this issue 4 years ago. :)

In other news, yet another case where lack of argument passing is a problem for Sailfish OS applications:
http://talk.maemo.org/showthread.php?t=100253&page=2

In short:
- a developer (Taixzo) would like to tell a Sailfish OS QML mapping application (WhoMaps) application to launch and zoom on a point
- this is not possible as sailfish-qml can't pass command line arguments to the application

**Comment by martyone** [comment]
@M4rtinK are you sure this issue really (still) exists? I just briefly checked the code and it seems like doing exactly what you suggested.

**Comment by otsaloma** [comment]
Just tried it, `Qt.application.arguments` does work indeed. Maybe it was this commit: https://github.com/sailfishos/libsailfishapp/commit/4b1ab9bd24744075e9f2e019838f28559ae2b6c4? Would have been nice to close this issue though.

**Comment by martyone** [comment]
@otsaloma thanks :)
